version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sge_user
      POSTGRES_PASSWORD: DJE20ben
      POSTGRES_DB: expedientes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.production
    depends_on:
      - postgres

  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist/browser:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data:
